feature/adaptTemplatesCobiGen
devonfw-tutorials/tutorial-compiler pull request #121
Opened 2021-02-15 14:01 UTC by denise-khuu

2021-02-15 15:02 UTC, GuentherJulian requested changes

2021-02-15 15:02 UTC, GuentherJulian commented on runners/console/index.ts
> +            .fileExits(path.join(this.getWorkingDirectory(), "devonfw", "software", "cobigen-cli", "class-loader-agent.jar"));
I think we don't need to check these two files because they should be installed with cobigen. But maybe we can check if the template folder exists.

2021-02-15 17:36 UTC, GuentherJulian requested changes

2021-02-15 17:36 UTC, GuentherJulian commented on runners/console/index.ts
> +            .directoryExits(path.join(homedir, ".cobigen", "templates"));
Also use the directoryNotEmpty assertion

2021-02-16 13:47 UTC, maybeec approved these changes

2021-02-17 07:10 UTC, merged