WP: wikirunner/cloneRepository
devonfw-tutorials/tutorial-compiler pull request #188
Opened 2021-04-07 13:29 UTC by MarcelDiessner

#175

2021-04-08 10:34 UTC, GuentherJulian requested changes

2021-04-08 10:34 UTC, GuentherJulian commented on runners/wikiConsole/templates/cloneRepository.asciidoc
> +=============
This line is too short, so the header is not displayed as a header line

2021-04-08 10:34 UTC, GuentherJulian commented on runners/wikiConsole/templates/cloneRepository.asciidoc
> +* Install git
You should mention here what to do to install Git

2021-04-09 11:41 UTC, GuentherJulian requested changes

2021-04-09 11:41 UTC, GuentherJulian commented on runners/wikiConsole/templates/cloneRepository.asciidoc
> +* You need to have git installed. You can download git https://git-scm.com/downloads[here] for your OS and install it by following the instructions.
Git is a name, so the first letter has to be always capital

2021-04-12 06:51 UTC, denise-khuu commented on runners/wikiConsole/templates/cloneRepository.asciidoc
> +If the directory does not exist yet, you can create by using the `mkdir` command in the terminal.
*create it

2021-04-13 10:26 UTC, GuentherJulian approved these changes

2021-04-13 12:15 UTC, denise-khuu approved these changes

2021-04-14 07:42 UTC, merged