Extend wikiConsole:installDevonfwIde
devonfw-tutorials/tutorial-compiler pull request #191
Opened 2021-04-08 08:57 UTC by derochs

2021-04-09 11:44 UTC, GuentherJulian requested changes

2021-04-09 11:44 UTC, GuentherJulian commented on runners/wikiConsole/templates/installDevonfwIde.asciidoc
> +After that you need to extract the downloaded file. To do this, run `tar -xvzf devonfw-ide-scripts.tar.gz`. Or you can simply use a tool (e.g. 7-Zip) for this.
This line in now redundant in the template. You can just move it below the if part

2021-04-11 13:50 UTC, GuentherJulian submitted a review, later dismissed

2021-04-11 19:00 UTC, maybeec requested changes

2021-04-11 19:00 UTC, maybeec commented on runners/wikiConsole/templates/installDevonfwIde.asciidoc
> +
What about Mac?

2021-04-13 13:07 UTC, denise-khuu approved these changes

2021-04-13 13:25 UTC, GuentherJulian approved these changes

2021-04-14 08:01 UTC, maybeec approved these changes

2021-04-14 08:18 UTC, merged