wikirunner/npmInstall
devonfw-tutorials/tutorial-compiler pull request #192
Opened 2021-04-09 08:23 UTC by MarcelDiessner

#178

2021-04-09 11:32 UTC, GuentherJulian requested changes

2021-04-09 11:32 UTC, GuentherJulian commented on runners/wikiConsole/templates/npmInstall.asciidoc
> +Install npm
You do not install npm in this step

2021-04-09 11:32 UTC, GuentherJulian commented on runners/wikiConsole/templates/npmInstall.asciidoc
> +First make sure to have installed npm. We recommend to install the devonfwIDE which includes an npm installation. Alternatively, you can download npm https://www.npmjs.com/get-npm[here] and follow th
npm and nodejs have to be installed

2021-04-09 11:32 UTC, GuentherJulian commented on runners/wikiConsole/templates/npmInstall.asciidoc
> +Then, you need to be located in the project directory where the package.json file lies.
You can use the npmInstall command without project directory, too. For example if you want to install a package globally

2021-04-09 14:36 UTC, GuentherJulian requested changes

2021-04-09 14:36 UTC, GuentherJulian commented on runners/wikiConsole/templates/npmInstall.asciidoc
> +npmInstall
The header should not only be the name of the command. It should describe shortly what is done

2021-04-13 13:11 UTC, denise-khuu approved these changes

2021-04-15 11:50 UTC, GuentherJulian requested changes

2021-04-15 11:50 UTC, GuentherJulian commented on runners/wikiConsole/templates/npmInstall.asciidoc
> +Installation of packages with npm install
I would find it better if you write the name of the package here if a package is given and write 'Install dependencies' if the user should install the packages from the package.json file

2021-04-20 15:44 UTC, GuentherJulian approved these changes

2021-04-21 06:40 UTC, merged