Add wikiConsole:dockerCompose
devonfw-tutorials/tutorial-compiler pull request #196
Opened 2021-04-13 12:33 UTC by derochs

2021-04-19 13:01 UTC, GuentherJulian requested changes

2021-04-19 13:01 UTC, GuentherJulian commented on runners/wikiConsole/templates/dockerCompose.asciidoc
> +Docker Compose can be used via your console. Change the directory to the location where the `docker-compose.yml` file for your application is located:
Better use terminal or command line than console

2021-04-19 13:01 UTC, GuentherJulian commented on runners/wikiConsole/templates/dockerCompose.asciidoc
> +~~~~~~~~~~~~~~
This is too short. So it is not displayed as header line

2021-04-21 12:51 UTC, GuentherJulian approved these changes

2021-04-22 08:13 UTC, denise-khuu approved these changes

2021-04-22 09:00 UTC, merged