WIP: wikirunner/buildJava
devonfw-tutorials/tutorial-compiler pull request #198
Opened 2021-04-14 11:19 UTC by MarcelDiessner

#171

2021-04-19 12:55 UTC, GuentherJulian requested changes

2021-04-19 12:55 UTC, GuentherJulian commented on runners/wikiConsole/templates/buildJava.asciidoc
> +Build a Java Project with Maven
Better write 'Build the Java Project with Maven' than 'Build a ...', because the output will refer to a specific project

2021-04-19 12:55 UTC, GuentherJulian commented on runners/wikiConsole/templates/buildJava.asciidoc
> +* You need to have Maven installed. If not already installed, you can download it https://maven.apache.org/download.cgi[here]. Alternativly, you can make use of the DevonfwIDE, where you can install
devonfw-ide

2021-04-19 12:55 UTC, GuentherJulian commented on runners/wikiConsole/templates/buildJava.asciidoc
> +Now move to your project directory manually or by executing `cd <%= directoryPath; %>` in the console.
Better write terminal or command line than console

2021-04-22 13:49 UTC, derochs commented
Merge conflicts due to updated `runners/wikiConsole/index.ts` on main branch need to be resolved

2021-04-23 12:29 UTC, GuentherJulian approved these changes

2021-04-30 08:14 UTC, merged