parser/tutorialConclusion
devonfw-tutorials/tutorial-compiler pull request #209
Opened 2021-04-16 08:54 UTC by MarcelDiessner

2021-04-19 08:13 UTC, EduardKrieger submitted a review, later dismissed

2021-04-19 12:40 UTC, GuentherJulian approved these changes

2021-04-19 13:38 UTC, GuentherJulian commented
There are some conflicts that must be resolved.
And could you add the method for the console runner (just an empty method, https://github.com/devonfw-tutorials/tutorial-compiler/issues/204) and maybe the wiki runner (https://github.com/devonfw-tutorials/tutorial-compiler/issues/205), too

2021-04-20 07:03 UTC, MarcelDiessner commented
> There are some conflicts that must be resolved.
> And could you add the method for the console runner (just an empty method, #204) and maybe the wiki runner (#205), too

I think the console runner version is not needed because i fill the finish.md file in the destroy method and not in a seperate one

2021-04-20 15:45 UTC, GuentherJulian submitted a review, later dismissed

2021-04-21 06:02 UTC, SchettlerKoehler requested changes

2021-04-21 06:02 UTC, SchettlerKoehler commented on engine/parser.def
> +  = descriptionline+ { return { "conclusionlines": text()}; }
I would duplicate the descriptionline token to avoid confusion.

2021-04-21 06:02 UTC, SchettlerKoehler commented on engine/parser.def
> +  	"====" ___
Use the blockmarker token

2021-04-21 06:03 UTC, SchettlerKoehler commented
Please inform @ssarmokadam when this is finished and merged.

2021-04-21 08:06 UTC, GuentherJulian approved these changes

2021-04-21 09:15 UTC, SchettlerKoehler approved these changes

2021-04-21 09:15 UTC, merged