Feature/wikiRunnerIntro
devonfw-tutorials/tutorial-compiler pull request #236
Opened 2021-05-06 13:04 UTC by EduardKrieger

2021-05-10 14:37 UTC, GuentherJulian requested changes

2021-05-10 14:37 UTC, GuentherJulian commented on runners/katacoda/templates/intro.md
> +Feel free to report any errors to us or fix them yourself. You just need to create a pull request to the https://github.com/devonfw-tutorials/tutorials[tutorials repository] with your changes.
In the first sentence you could mention that the errors can be reported by creating an issue in the tutorials repo. Also in the wiki template

2021-05-14 11:27 UTC, GuentherJulian requested changes

2021-05-14 11:27 UTC, GuentherJulian commented on runners/wikiConsole/templates/intro.asciidoc
> +Feel free to report any errors to us or fix them yourself. Errors can be reported by creating an issue in the https://github.com/devonfw-tutorials/tutorials[tutorials repository]. To fix the error fo
You can use the direct link to the issues site here
https://github.com/devonfw-tutorials/tutorials/issues
And add this section also to the katacoda intro template

2021-05-21 10:16 UTC, denise-khuu approved these changes

2021-05-21 10:43 UTC, GuentherJulian approved these changes

2021-05-21 10:43 UTC, merged