Feature/wikirunnerCreateDevon4jProject
devonfw-tutorials/tutorial-compiler pull request #237
Opened 2021-05-07 07:51 UTC by MarcelDiessner

closes #170

2021-05-09 14:27 UTC, EduardKrieger submitted a review, later dismissed

2021-05-09 16:15 UTC, EduardKrieger commented on runners/wikiEclipse/templates/createDevon4jProject.asciidoc
> +Fill the Group Id, Artifact Id, Version and Package for your project. The package name should be <%= name; %>.
Maybe try to highlight the labels of some text field like  *Group Id* for better visibility where the user has to insert something.

2021-05-10 14:51 UTC, GuentherJulian requested changes

2021-05-10 14:51 UTC, GuentherJulian commented on runners/wikiConsole/templates/createDevon4jProject.asciidoc
> +=== Create a new Devon4j Project from command prompt
devon4j and project in lower cases. Also in the rest of the template

2021-05-10 14:51 UTC, GuentherJulian commented on runners/wikiConsole/templates/createDevon4jProject.asciidoc
> +==== What is generated
==== What is generated?

2021-05-10 14:51 UTC, GuentherJulian commented on runners/wikiConsole/templates/createDevon4jProject.asciidoc
> +- *api*: module with the API (REST service interfaces, transferobjects, datatypes, etc.) to be imported by other apps as a maven dependency in order to invoke and consume the offered (micro)services.
transfer-objects

2021-05-10 14:51 UTC, GuentherJulian commented on runners/wikiConsole/templates/createDevon4jProject.asciidoc
> +- *ear*: optional maven module is responsible to packaging the application as a EAR file.
Is an ear module created by default?

2021-05-10 14:51 UTC, GuentherJulian commented on runners/wikiConsole/templates/createDevon4jProject.asciidoc
> +The application template (archetype) generates a Maven multi-module project. It has the following modules:
Sometimes you write Maven in lowercase letters and sometimes in uppercase letters. You should use the same writing everywhere. On the devonfw page the lower case version is used

2021-05-14 08:29 UTC, GuentherJulian approved these changes

2021-05-14 10:25 UTC, merged