Feature/wikiRunnerInstallCobiGen
devonfw-tutorials/tutorial-compiler pull request #244
Opened 2021-05-09 14:18 UTC by EduardKrieger

2021-05-10 15:08 UTC, GuentherJulian requested changes

2021-05-10 15:08 UTC, GuentherJulian commented on runners/wikiConsole/templates/installCobiGen.asciidoc
> +Installing devonfw CodeGenerator(i.e. CobiGen).
code generator

2021-05-10 15:08 UTC, GuentherJulian commented on runners/wikiConsole/templates/installCobiGen.asciidoc
> +Execute the command `devon conigen` and CobiGen will be installed.
devon cobigen

2021-05-10 15:08 UTC, GuentherJulian commented on runners/wikiVsCode/templates/installCobiGen.asciidoc
> +CobiGen is already installed for your VSCode Editor if you have installed it with the devonfw setup.
The VS Code plugin is currently not automatically installed within the devon ide. The plugin is available on https://github.com/devonfw-forge/cobigen-vscode-plugin and has to be installed manually. The user can do this via command line or in VS Code via the Command Palette.

2021-05-12 09:58 UTC, EduardKrieger commented on engine/wikiRunner.ts
> +    protected readonly installedTools: string = "installedTools";
I wanted to use it like in the runner.ts [https://github.com/devonfw-tutorials/tutorial-compiler/blob/5782eaf568ce232749fbe6baa61fc0af9491770c/engine/runner.ts#L14-L15](url). Also, I cant set it to a empty string at this place.

2021-05-12 11:46 UTC, denise-khuu commented on engine/wikiRunner.ts
> +    protected readonly installedTools: string = "installedTools";
I think there is a best practice to name const variables in capital case. We could think about renaming them to prevent such confusions.

2021-05-12 11:49 UTC, denise-khuu commented on runners/wikiConsole/templates/installCobiGen.asciidoc
> +First, you need to open a command prompt in your current Workspace. For Windows, you can use PowerShell and on Linux and macOS, you can use the Terminal.
*workspace

2021-05-14 11:23 UTC, GuentherJulian requested changes

2021-05-14 11:23 UTC, GuentherJulian commented on runners/wikiVsCode/templates/installCobiGen.asciidoc
> +First, download the VS Code extension file. You can download it https://github.com/devonfw-forge/cobigen-vscode-plugin/releases/download/0.0.1/cobigen-plugin-0.0.1.vsix[here] or execute this command
download it from ...
execute the following command ...

2021-05-14 11:23 UTC, GuentherJulian commented on runners/wikiConsole/templates/installCobiGen.asciidoc
> +* An installed devonfw distribution is needed. To execute the cobigen CLI, you have to install the devonfw IDE first. Follow the https://devonfw.com/website/pages/docs/devonfw-ide-introduction.asciid
CobiGen CLI

2021-05-26 06:37 UTC, denise-khuu commented on runners/wikiEclipse/templates/installCobigen.asciidoc
> +You can open the *Help* menu and select *About Eclipse IDE*. To check if CobiGen is installed select *Installation Details* and CobiGen should be in the List of *Installed Software* and *Plug-ins*. Y
*list

2021-05-27 06:36 UTC, denise-khuu approved these changes

2021-05-27 07:13 UTC, GuentherJulian requested changes

2021-05-27 07:13 UTC, GuentherJulian commented on runners/wikiConsole/index.ts
> +import { Console } from "console";
Is this needed?

2021-05-31 07:51 UTC, denise-khuu approved these changes

2021-05-31 09:35 UTC, GuentherJulian approved these changes

2021-05-31 09:36 UTC, merged