Update function installCobiGen
devonfw-tutorials/tutorial-compiler pull request #302
Opened 2021-07-29 07:48 UTC by dixyushi

2021-08-03 08:41 UTC, GuentherJulian approved these changes

2021-08-03 18:24 UTC, EduardKrieger requested changes

2021-08-03 18:24 UTC, EduardKrieger commented on documentation/Functions.md
> +Note: User needs to execute this command manually.
Add devonfw-ide has to be installed.

2021-08-12 08:16 UTC, GuentherJulian submitted a review, later dismissed

2021-08-12 12:42 UTC, dixyushi commented on documentation/Functions.md
> +1. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Done!!

2021-08-12 12:43 UTC, dixyushi commented on documentation/Functions.md
> +This function is used to install the CobiGen CLI inside devonfw IDE.
Done!!

2021-08-13 12:18 UTC, merged