Update function create folder
devonfw-tutorials/tutorial-compiler pull request #303
Opened 2021-07-29 09:49 UTC by dixyushi

2021-08-03 08:48 UTC, GuentherJulian requested changes

2021-08-03 08:48 UTC, GuentherJulian commented on documentation/Functions.md
> +This function is used when you want to use an other command in a location which does not exist at the moment
I would simply write: This function creates a new folder
And then you can mention that one can use this when wanting to run other commands (e.g. createFile) in locations that does not exist at the moment

2021-08-03 17:45 UTC, EduardKrieger commented on documentation/Functions.md
> +You need to add only one parameter.
pass only one parameter

2021-08-06 15:48 UTC, EduardKrieger requested changes

2021-08-06 15:48 UTC, EduardKrieger commented on documentation/Functions.md
> +This function has only one parameter.
For some functions you are using  `This function consist of two parameters.` this should be consistent.

2021-08-12 08:17 UTC, GuentherJulian requested changes

2021-08-12 08:17 UTC, GuentherJulian commented on documentation/Functions.md
> +1. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 12:40 UTC, dixyushi commented on documentation/Functions.md
> +1. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Done!!

2021-08-13 08:28 UTC, merged