Update function npm install
devonfw-tutorials/tutorial-compiler pull request #304
Opened 2021-07-29 10:48 UTC by dixyushi

2021-08-03 09:06 UTC, GuentherJulian requested changes

2021-08-03 09:06 UTC, GuentherJulian commented on documentation/Functions.md
> +1st-parameter: It is always needed. It is the path to the project where the dependencies from the package.json file are to be installed. It is of type string.
I think we don't need to mention when a parameter is explicitly required. Just mention when a parameter is optional

2021-08-03 09:06 UTC, GuentherJulian commented on documentation/Functions.md
> +2nd-parameter: It is optional. It is the array of Json-objects which contains Name of a package, global or local installation, or array of npm arguments.
JSON in uppercase. name with leading lowercase.

2021-08-03 17:53 UTC, EduardKrieger commented on documentation/Functions.md
> +You need to two parameters for this function.
Try to use the same wording for every function. I would prefer if you take: "You need to pass two parameters for this function"

2021-08-12 08:19 UTC, GuentherJulian requested changes

2021-08-12 08:19 UTC, GuentherJulian commented on documentation/Functions.md
> +npmInstall is used for installing packages from node package mangager, for example used in nodejs or angular projects.
Node.js or Angular

2021-08-12 08:19 UTC, GuentherJulian commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 12:32 UTC, dixyushi commented on documentation/Functions.md
> +npmInstall is used for installing packages from node package mangager, for example used in nodejs or angular projects.
Changed!!

2021-08-12 12:32 UTC, dixyushi commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Changed!!

2021-08-13 08:28 UTC, merged