Update function execute command
devonfw-tutorials/tutorial-compiler pull request #305
Opened 2021-07-29 11:09 UTC by dixyushi

2021-08-04 15:55 UTC, dixyushi commented on documentation/Functions.md
> +* executeCommand("somePollingScript.ps1","bash somePollingScript.sh", {"dir": "data/setup","asynchronous": true, "args": ["--params 5"]})
done

2021-08-04 15:55 UTC, dixyushi commented on documentation/Functions.md
> +This function is used when you want to use a bash (or powershell/cmd on windows) command.
Edited it.

2021-08-12 08:21 UTC, GuentherJulian requested changes

2021-08-12 08:21 UTC, GuentherJulian commented on documentation/Functions.md
> +1. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 12:29 UTC, dixyushi commented on documentation/Functions.md
> +1. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Changed!!

2021-08-13 12:14 UTC, merged