Update function createDevon4jProject
devonfw-tutorials/tutorial-compiler pull request #306
Opened 2021-07-29 16:44 UTC by suvmanda

2021-08-03 09:13 UTC, GuentherJulian requested changes

2021-08-03 09:13 UTC, GuentherJulian commented on documentation/Functions.md
>  ### createDevon4jProject <a name="createDevon4jProject"></a>
This function is used to create a [devon4j](https://github.com/devonfw/devon4j) project.

2021-08-03 09:13 UTC, GuentherJulian requested changes

2021-08-03 09:13 UTC, GuentherJulian commented on documentation/Functions.md
> +This function is used to create devon4j project.
This function is used to create a [devon4j](https://github.com/devonfw/devon4j) project.

2021-08-04 11:00 UTC, EduardKrieger requested changes

2021-08-12 08:22 UTC, GuentherJulian requested changes

2021-08-12 08:22 UTC, GuentherJulian commented on documentation/Functions.md
> +1. This function generates command the katacoda user has to execute manually.
Katacoda with starting capital letter

2021-08-13 09:18 UTC, merged