update function documentation buildJava
devonfw-tutorials/tutorial-compiler pull request #307
Opened 2021-07-30 04:32 UTC by suvmanda

2021-08-03 09:26 UTC, GuentherJulian requested changes

2021-08-03 09:26 UTC, GuentherJulian commented on documentation/Functions.md
> +There is two parameter you need to use.
There are...

2021-08-04 11:08 UTC, EduardKrieger requested changes

2021-08-04 11:08 UTC, EduardKrieger commented on documentation/Functions.md
> +There are two parameter you need to use.
You need to use just one parameter the other is optional, maybe say the function consist of 2 parameters and after that the parameter definition as a list.

2021-08-12 08:23 UTC, GuentherJulian approved these changes

2021-08-13 08:30 UTC, merged