updated cloneRepository function
devonfw-tutorials/tutorial-compiler pull request #311
Opened 2021-08-02 07:51 UTC by dixyushi

2021-08-03 10:01 UTC, GuentherJulian requested changes

2021-08-03 10:01 UTC, GuentherJulian commented on documentation/Functions.md
> +2nd-parameter: It is the git repository URL. It is of type String.
Git with leading capital letter

2021-08-04 16:07 UTC, dixyushi commented on documentation/Functions.md
> +This function is used when you want to clone a repository into a particular repository.
changed

2021-08-04 16:07 UTC, dixyushi commented on documentation/Functions.md
> +2nd-parameter: It is the git repository URL. It is of type String.
done

2021-08-12 08:42 UTC, GuentherJulian requested changes

2021-08-12 08:42 UTC, GuentherJulian commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 12:27 UTC, dixyushi commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Changed!!

2021-08-13 08:33 UTC, merged