Updated docker-compose function
devonfw-tutorials/tutorial-compiler pull request #314
Opened 2021-08-02 10:06 UTC by dixyushi

2021-08-03 10:22 UTC, GuentherJulian requested changes

2021-08-03 10:22 UTC, GuentherJulian commented on documentation/Functions.md
> +This function is used for docker compose.
This function is used to running [Docker Compose](https://docs.docker.com/compose/).

2021-08-03 10:22 UTC, GuentherJulian commented on documentation/Functions.md
> +3.  Docker should be installed.
Docker must be installed. In the Katacoda environment, Docker is already preinstalled.

2021-08-12 08:50 UTC, GuentherJulian requested changes

2021-08-12 08:50 UTC, GuentherJulian commented on documentation/Functions.md
> +3. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 08:50 UTC, GuentherJulian commented on documentation/Functions.md
> +5. TO use this function, devonfw-ide must be installed.
devonfw-ide has not to be installed. Only Docker which is preinstalled in Katacoda as you mentioned above.

2021-08-12 12:21 UTC, dixyushi commented on documentation/Functions.md
> +3. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
done!

2021-08-13 08:35 UTC, merged