Updated adaptCobiGenTemplates function
devonfw-tutorials/tutorial-compiler pull request #316
Opened 2021-08-02 10:23 UTC by dixyushi

2021-08-03 10:41 UTC, GuentherJulian requested changes

2021-08-03 10:41 UTC, GuentherJulian commented on documentation/Functions.md
> +This function is used when you want to adapt CobiGen templates.
This function is used when you want to adapt CobiGen templates. See [CobiGen CLI documentation](https://devonfw.com/website/pages/docs/howto_Cobigen-CLI-generation.asciidoc.html).

2021-08-03 10:41 UTC, GuentherJulian commented on documentation/Functions.md
> +2. To execute this command first you need to execute installCobiGen() function to install CobiGen. For this function CobiGen needs to be installed.
Mention only once that CobiGen must be installed.

2021-08-12 08:55 UTC, GuentherJulian requested changes

2021-08-12 08:55 UTC, GuentherJulian commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
Katacoda

2021-08-12 12:15 UTC, dixyushi commented on documentation/Functions.md
> +2. The command for execution will be generated by katacoda runner, so user will have to execute this command manually.
done!!

2021-08-13 08:36 UTC, merged